# Experiment settings

# Experiment repository
experiment-repo: "demo-experiment"  # github repo name
organisation: "techtile-by-dramco"  # github org

# Tile settings
#tiles: "segmentA"                   # group name, single tile, or space-separated list
tiles: "A05 A06 A07 A08 A09 A10"    # group name, single tile, or space-separated list

extra-packages:                     # list of extra packages to be installed on the tiles' rpi's
  - python3-numpy
  - python3-scipy
  - python3-zmq

# Server script behaviour
test-connectivity: True             # set True if you want to test tile connectivity before continuing.
halt-on-connectivity-failure: True  # set False if you want to continue with only the active tiles
